# Generated by Django 4.0.4 on 2022-05-26 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='room number')),
                ('price', models.IntegerField(help_text='price of room for one day')),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='booking name', max_length=100)),
                ('from_date', models.DateField(help_text='reservation start date')),
                ('to_date', models.DateField(help_text='reservation end date')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_factors', to='rooms.room')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
    ]
