# Generated by Django 4.0.4 on 2022-05-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.PositiveIntegerField(help_text='room number', unique=True),
        ),
    ]
